// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[image].tsx";
import * as $1 from "./routes/color/[color].tsx";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/yellow.tsx";
import * as $$0 from "./islands/ButtonRouter.tsx";
import * as $$1 from "./islands/ButtonRouterColor.tsx";
import * as $$2 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/[image].tsx": $0,
    "./routes/color/[color].tsx": $1,
    "./routes/index.tsx": $2,
    "./routes/yellow.tsx": $3,
  },
  islands: {
    "./islands/ButtonRouter.tsx": $$0,
    "./islands/ButtonRouterColor.tsx": $$1,
    "./islands/Counter.tsx": $$2,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
